charts:
    - name: "dotty (source changes over time)"
      url: https://github.com/lampepfl/dotty
      lines:
        - key:  dotty
          label: bootstrapped
        - key:  dotty-sbt
          label: with sbt phases

    - name: "scala stdlib-2.13"
      url: https://github.com/dotty-staging/scala/commits/stdLib213-dotty-community-build
      lines:
        - key: stdlib213
          label: bootstrapped

    - name: scalap
      url: https://github.com/dotty-staging/scala/commits/scalap-dotty-community-build-2.13
      lines:
        - key: scalap
          label: bootstrapped

    - name: re2
      url: https://github.com/lampepfl/bench/blob/master/tests/re2s
      lines:
        - key: re2s
          label: bootstrapped

    - name: "implicit cache I"
      url: https://github.com/lampepfl/dotty/blob/master/tests/bench/implicit_cache.scala
      lines:
        - key: implicit-cache
          label: bootstrapped
        - key: implicit-cache-from-tasty
          label: from tasty

    - name: "implicit cache II"
      url: https://github.com/lampepfl/dotty/blob/master/tests/bench/implicitNums.scala
      lines:
        - key: implicitNums
          label: bootstrapped
        - key: implicitNums-from-tasty
          label: from tasty

    - name: "implicit scope loop"
      url: https://github.com/lampepfl/dotty/blob/master/tests/bench/implicit-scope-loop.scala
      lines:
        - key: implicit-scope-loop
          label: bootstrapped

    - name: "inductive implicits"
      url: https://github.com/lampepfl/dotty/blob/master/tests/bench/inductive-implicits.scala
      lines:
        - key: inductive-implicits
          label: bootstrapped

    - name: "exhaustivity check"
      url: https://github.com/lampepfl/dotty/blob/master/tests/bench/patmatexhaust.scala
      lines:
        - key: patmatexhaust
          label: bootstrapped

    - name: "exhaustivity I"
      url: https://github.com/lampepfl/dotty/blob/master/tests/bench/exhaustivity-I.scala
      lines:
        - key: exhaustivity-I
          label: bootstrapped

    - name: "exhaustivity S"
      url: https://github.com/lampepfl/dotty/blob/master/tests/bench/exhaustivity-S.scala
      lines:
        - key: exhaustivity-S
          label: bootstrapped

    - name: "exhaustivity T"
      url: https://github.com/lampepfl/dotty/blob/master/tests/bench/exhaustivity-T.scala
      lines:
        - key: exhaustivity-T
          label: bootstrapped

    - name: "exhaustivity V"
      url: https://github.com/lampepfl/dotty/blob/master/tests/bench/exhaustivity-V.scala
      lines:
        - key: exhaustivity-V
          label: bootstrapped

    - name: "exhaustivity MIPS"
      url: https://github.com/lampepfl/dotty/blob/master/tests/patmat/i7186.scala
      lines:
        - key: exhaustivity-mips
          label: bootstrapped

    - name: "issue #1535"
      url: https://github.com/lampepfl/dotty/blob/master/tests/bench/i1535.scala
      lines:
        - key: i1535
          label: bootstrapped

    - name: "issue #1687"
      url: https://github.com/lampepfl/dotty/blob/master/tests/bench/i1687.scala
      lines:
        - key: i1687
          label: bootstrapped

    - name: "empty class"
      url: https://github.com/lampepfl/dotty/blob/master/tests/bench/empty-class.scala
      lines:
        - key: empty-class
          label: bootstrapped

    - name: "empty object"
      url: https://github.com/lampepfl/dotty/blob/master/tests/bench/empty-object.scala
      lines:
        - key: empty-object
          label: bootstrapped

    - name: "empty file"
      url: https://github.com/lampepfl/dotty/blob/master/tests/bench/empty-file.scala
      lines:
        - key: empty-file
          label: bootstrapped

    - name: "Inline a quote"
      url: https://github.com/lampepfl/dotty/blob/master/tests/bench/power-macro/PowerInlined-1.scala
      lines:
        - key: power-macro-power-inlined-1
          label: bootstrapped

    - name: "Inline 1k quotes"
      url: https://github.com/lampepfl/dotty/blob/master/tests/bench/power-macro/PowerInlined-1k.scala
      lines:
        - key: power-macro-power-inlined-1k
          label: bootstrapped

    - name: "Tuple22 creation with Tuple22.apply"
      url: https://github.com/lampepfl/dotty/blob/master/tests/bench/tuple22-creation-apply.scala
      lines:
        - key: tuple22-creation-apply
          label: bootstrapped

    - name: "Tuple22 creation with *:"
      url: https://github.com/lampepfl/dotty/blob/master/tests/bench/tuple22-creation-cons.scala
      lines:
        - key: tuple22-creation-cons
          label: bootstrapped

    - name: "Tuple22.tail"
      url: https://github.com/lampepfl/dotty/blob/master/tests/bench/tuple22-tails.scala
      lines:
        - key: tuple22-tails
          label: bootstrapped

    - name: "Tuple22.apply"
      url: https://github.com/lampepfl/dotty/blob/master/tests/bench/tuple22-apply.scala
      lines:
        - key: tuple22-apply
          label: bootstrapped

    - name: "Tuple22.size"
      url: https://github.com/lampepfl/dotty/blob/master/tests/bench/tuple22-size.scala
      lines:
        - key: tuple22-size
          label: bootstrapped

    - name: "Tuple reverse (Runtime)"
      url: https://github.com/lampepfl/dotty/blob/master/bench-run/src/main/scala/dotty/tools/benchmarks/tuples/TupleOps.scala#L59
      lines:
        - key: tuple-reverse
          label: bootstrapped

    - name: "Tuple flatMap (Runtime)"
      url: https://github.com/lampepfl/dotty/blob/master/bench-run/src/main/scala/dotty/tools/benchmarks/tuples/TupleOps.scala#L64
      lines:
        - key: tuple-flatMap
          label: bootstrapped

scripts:
    dotty:
        - measure -with-compiler $(find $PROG_HOME/dotty/compiler/src/dotty -name *.scala -o -name *.java)

    dotty-sbt:
        - measure -with-compiler -Yforce-sbt-phases $(find $PROG_HOME/dotty/compiler/src/dotty -name *.scala -o -name *.java)

    re2s:
        - measure $(find $PROG_HOME/tests/re2s/src -name *.scala)

    implicit-cache:
        - measure $PROG_HOME/dotty/tests/bench/implicit_cache.scala

    implicit-cache-from-tasty:
        - source $PROG_HOME/tests/scripts/implicit-cache-from-tasty

    implicit-scope-loop:
        - measure $PROG_HOME/dotty/tests/bench/implicit-scope-loop.scala

    inductive-implicits:
        - measure $PROG_HOME/dotty/tests/bench/inductive-implicits.scala

    i1535:
        - measure $PROG_HOME/dotty/tests/bench/i1535.scala

    i1687:
        - measure $PROG_HOME/dotty/tests/bench/i1687.scala

    empty-class:
        - measure $PROG_HOME/dotty/tests/bench/empty-class.scala

    empty-object:
        - measure $PROG_HOME/dotty/tests/bench/empty-object.scala

    empty-file:
        - measure $PROG_HOME/dotty/tests/bench/empty-file.scala

    patmatexhaust:
        - measure 20 40 3 $PROG_HOME/dotty/tests/bench/patmatexhaust.scala

    exhaustivity-I:
        - measure 20 40 3 $PROG_HOME/dotty/tests/bench/exhaustivity-I.scala

    exhaustivity-S:
        - measure 20 40 3 $PROG_HOME/dotty/tests/bench/exhaustivity-S.scala

    exhaustivity-T:
        - measure 20 40 3 $PROG_HOME/dotty/tests/bench/exhaustivity-T.scala

    exhaustivity-V:
        - measure 20 40 3 $PROG_HOME/dotty/tests/bench/exhaustivity-V.scala

    exhaustivity-mips:
        - measure 20 40 3 $PROG_HOME/dotty/tests/patmat/i7186.scala

    implicitNums:
        - measure $PROG_HOME/dotty/tests/bench/implicitNums.scala

    implicitNums-from-tasty:
        - source $PROG_HOME/tests/scripts/implicitNums-from-tasty

    # scalapb:
    #    - source $PROG_HOME/tests/scripts/scalapb

    scalap:
       - source $PROG_HOME/tests/scripts/scalap

    power-macro-power-inlined-1:
        - source $PROG_HOME/tests/scripts/power-macro-1

    power-macro-power-inlined-1k:
        - source $PROG_HOME/tests/scripts/power-macro-1k

    stdlib213:
        - source $PROG_HOME/tests/scripts/stdlib213

    tuple22-creation-apply:
        - measure $PROG_HOME/dotty/tests/bench/tuple22-creation-apply.scala

    tuple22-creation-cons:
        - measure $PROG_HOME/dotty/tests/bench/tuple22-creation-cons.scala

    tuple22-tails:
        - measure $PROG_HOME/dotty/tests/bench/tuple22-tails.scala

    tuple22-apply:
        - measure $PROG_HOME/dotty/tests/bench/tuple22-apply.scala

    tuple22-size:
        - measure $PROG_HOME/dotty/tests/bench/tuple22-size.scala

    tuple-reverse:
        - measure-run TupleOps.reverse

    tuple-flatMap:
        - measure-run TupleOps.flatMap

config:
    pr_base_url: "https://github.com/lampepfl/dotty/pull/"
