var Bench = Bench || {}
Bench.charts = [
{"name":"dotty (source changes over time)","url":"https://github.com/lampepfl/dotty","lines":[{"key":"dotty","label":"bootstrapped"}]},
{"name":"scala stdlib-2.13","url":"https://github.com/dotty-staging/scala/commits/stdLib213-dotty-community-build","lines":[{"key":"stdlib213","label":"bootstrapped"}]},
{"name":"scalap","url":"https://github.com/dotty-staging/scala/commits/scalap-dotty-community-build-2.13","lines":[{"key":"scalap","label":"bootstrapped"}]},
{"name":"re2","url":"https://github.com/lampepfl/bench/blob/master/tests/re2s","lines":[{"key":"re2s","label":"bootstrapped"}]},
{"name":"implicit cache I","url":"https://github.com/lampepfl/dotty/blob/master/tests/bench/implicit_cache.scala","lines":[{"key":"implicit-cache","label":"bootstrapped"},{"key":"implicit-cache-from-tasty","label":"from tasty"}]},
{"name":"implicit cache II","url":"https://github.com/lampepfl/dotty/blob/master/tests/bench/implicitNums.scala","lines":[{"key":"implicitNums","label":"bootstrapped"},{"key":"implicitNums-from-tasty","label":"from tasty"}]},
{"name":"implicit scope loop","url":"https://github.com/lampepfl/dotty/blob/master/tests/bench/implicit-scope-loop.scala","lines":[{"key":"implicit-scope-loop","label":"bootstrapped"}]},
{"name":"inductive implicits","url":"https://github.com/lampepfl/dotty/blob/master/tests/bench/inductive-implicits.scala","lines":[{"key":"inductive-implicits","label":"bootstrapped"}]},
{"name":"exhaustivity check","url":"https://github.com/lampepfl/dotty/blob/master/tests/bench/patmatexhaust.scala","lines":[{"key":"patmatexhaust","label":"bootstrapped"}]},
{"name":"exhaustivity I","url":"https://github.com/lampepfl/dotty/blob/master/tests/bench/exhaustivity-I.scala","lines":[{"key":"exhaustivity-I","label":"bootstrapped"}]},
{"name":"exhaustivity S","url":"https://github.com/lampepfl/dotty/blob/master/tests/bench/exhaustivity-S.scala","lines":[{"key":"exhaustivity-S","label":"bootstrapped"}]},
{"name":"exhaustivity T","url":"https://github.com/lampepfl/dotty/blob/master/tests/bench/exhaustivity-T.scala","lines":[{"key":"exhaustivity-T","label":"bootstrapped"}]},
{"name":"exhaustivity V","url":"https://github.com/lampepfl/dotty/blob/master/tests/bench/exhaustivity-V.scala","lines":[{"key":"exhaustivity-V","label":"bootstrapped"}]},
{"name":"exhaustivity MIPS","url":"https://github.com/lampepfl/dotty/blob/master/tests/patmat/i7186.scala","lines":[{"key":"exhaustivity-mips","label":"bootstrapped"}]},
{"name":"issue #1535","url":"https://github.com/lampepfl/dotty/blob/master/tests/bench/i1535.scala","lines":[{"key":"i1535","label":"bootstrapped"}]},
{"name":"issue #1687","url":"https://github.com/lampepfl/dotty/blob/master/tests/bench/i1687.scala","lines":[{"key":"i1687","label":"bootstrapped"}]},
{"name":"empty class","url":"https://github.com/lampepfl/dotty/blob/master/tests/bench/empty-class.scala","lines":[{"key":"empty-class","label":"bootstrapped"}]},
{"name":"empty object","url":"https://github.com/lampepfl/dotty/blob/master/tests/bench/empty-object.scala","lines":[{"key":"empty-object","label":"bootstrapped"}]},
{"name":"empty file","url":"https://github.com/lampepfl/dotty/blob/master/tests/bench/empty-file.scala","lines":[{"key":"empty-file","label":"bootstrapped"}]},
{"name":"Inline a quote","url":"https://github.com/lampepfl/dotty/blob/master/tests/bench/power-macro/PowerInlined-1.scala","lines":[{"key":"power-macro-power-inlined-1","label":"bootstrapped"}]},
{"name":"Inline 1k quotes","url":"https://github.com/lampepfl/dotty/blob/master/tests/bench/power-macro/PowerInlined-1k.scala","lines":[{"key":"power-macro-power-inlined-1k","label":"bootstrapped"}]},
{"name":"Quote String interpolation matching","url":"https://github.com/lampepfl/dotty/blob/master/tests/bench/string-interpolation-macro/Test.scala","lines":[{"key":"quote-string-interpolation-matching","label":"bootstrapped"}]},
{"name":"Tuple22 creation with Tuple22.apply","url":"https://github.com/lampepfl/dotty/blob/master/tests/bench/tuple22-creation-apply.scala","lines":[{"key":"tuple22-creation-apply","label":"bootstrapped"}]},
{"name":"Tuple22 creation with *:","url":"https://github.com/lampepfl/dotty/blob/master/tests/bench/tuple22-creation-cons.scala","lines":[{"key":"tuple22-creation-cons","label":"bootstrapped"}]},
{"name":"Tuple22.tail","url":"https://github.com/lampepfl/dotty/blob/master/tests/bench/tuple22-tails.scala","lines":[{"key":"tuple22-tails","label":"bootstrapped"}]},
{"name":"Tuple22.apply","url":"https://github.com/lampepfl/dotty/blob/master/tests/bench/tuple22-apply.scala","lines":[{"key":"tuple22-apply","label":"bootstrapped"}]},
{"name":"Tuple22.size","url":"https://github.com/lampepfl/dotty/blob/master/tests/bench/tuple22-size.scala","lines":[{"key":"tuple22-size","label":"bootstrapped"}]},
{"name":"Tuple reverse (Runtime)","url":"https://github.com/lampepfl/dotty/blob/master/bench-run/src/main/scala/dotty/tools/benchmarks/tuples/TupleOps.scala#L59","lines":[{"key":"tuple-reverse","label":"bootstrapped"}]},
{"name":"Tuple flatMap (Runtime)","url":"https://github.com/lampepfl/dotty/blob/master/bench-run/src/main/scala/dotty/tools/benchmarks/tuples/TupleOps.scala#L64","lines":[{"key":"tuple-flatMap","label":"bootstrapped"}]}
]
Bench.config = {"pr_base_url":"https://github.com/lampepfl/dotty/pull/"}
