#!/bin/bash

mkdir "$PROG_HOME/tests/power-macro/out"

compile -d "$PROG_HOME/tests/power-macro/out" "$PROG_HOME/tests/PowerMacro.scala"

measure "$PROG_HOME/tests/PowerInlined-1.scala" -classpath "$PROG_HOME/tests/power-macro/out"
measure "$PROG_HOME/tests/PowerInlined-1k.scala" -classpath "$PROG_HOME/tests/power-macro/out"
