#!/bin/bash

mkdir "$PROG_HOME/tests/power-macro/out"

dotc -d "$PROG_HOME/tests/power-macro/out" PowerMacro.scala

measure "tests/PowerInlined-1.scala" -classpath "$PROG_HOME/tests/power-macro/out"
measure "tests/PowerInlined-1k.scala" -classpath "$PROG_HOME/tests/power-macro/out"
