#!/bin/bash

cd $PROG_HOME/tests/scalapb
sbt runtimeJVM/compile:packCopyDependencies
rm scalapb-runtime/jvm/target/lib/scalapb*
rm scalapb-runtime/jvm/target/lib/root*

cd $PROG_HOME
measure -language:Scala2 -classpath "tests/scalapb/scalapb-runtime/jvm/target/lib/*"  $(find tests/scalapb/scalapb-runtime/jvm/src/main -name "*.scala") $(find tests/scalapb/scalapb-runtime/shared/src/main -name "*.scala")
